# Generated by Django 2.2.8 on 2020-01-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmail1',
            fields=[
                ('company_name', models.CharField(blank=True, db_column='Company_Name', max_length=50, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=35, null=True)),
                ('email_address', models.CharField(blank=True, db_column='Email_Address', max_length=50, primary_key=True, serialize=False)),
                ('application_date', models.DateTimeField(blank=True, db_column='Application_Date', null=True)),
            ],
            options={
                'db_table': 'company_email1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('dateofreading', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=30, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=30, null=True)),
                ('resource', models.TextField(blank=True, db_column='Resource', null=True)),
                ('online_resource', models.CharField(blank=True, db_column='Online_Resource', max_length=30, null=True)),
            ],
            options={
                'db_table': 'knowledge_base',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dateofreading', models.DateTimeField()),
                ('temperature', models.CharField(blank=True, max_length=10, null=True)),
                ('humidity', models.DecimalField(blank=True, db_column='Humidity', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'readings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReadingsSonar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dateofreading', models.DateTimeField()),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'readings_sonar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReadingsSonarDist',
            fields=[
                ('dateofreading', models.DateTimeField(primary_key=True, serialize=False)),
                ('distance', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'readings_sonar_dist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReadingsTemp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dateofreading', models.DateTimeField()),
                ('temperature', models.CharField(blank=True, max_length=10, null=True)),
                ('humidity', models.CharField(blank=True, db_column='Humidity', max_length=10, null=True)),
            ],
            options={
                'db_table': 'readings_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoStat',
            fields=[
                ('id', models.CharField(blank=True, db_column='ID', max_length=50, primary_key=True, serialize=False)),
                ('viewcount', models.CharField(blank=True, db_column='viewCount', max_length=10, null=True)),
                ('likecount', models.CharField(blank=True, db_column='likeCount', max_length=10, null=True)),
                ('favoritecount', models.CharField(blank=True, db_column='favoriteCount', max_length=10, null=True)),
                ('commentcount', models.CharField(blank=True, db_column='commentCount', max_length=10, null=True)),
                ('dislikecount', models.CharField(blank=True, db_column='dislikeCount', max_length=10, null=True)),
            ],
            options={
                'db_table': 'video_stat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoStatTableDf',
            fields=[
                ('id', models.CharField(blank=True, max_length=11, primary_key=True, serialize=False)),
                ('view_count', models.CharField(blank=True, db_column='view_Count', max_length=10, null=True)),
                ('like_count', models.CharField(blank=True, db_column='like_Count', max_length=7, null=True)),
                ('favorite_count', models.CharField(blank=True, db_column='favorite_Count', max_length=4, null=True)),
                ('comment_count', models.CharField(blank=True, db_column='comment_Count', max_length=6, null=True)),
                ('dislike_count', models.CharField(blank=True, db_column='dislike_Count', max_length=6, null=True)),
            ],
            options={
                'db_table': 'video_stat_table_df',
                'managed': False,
            },
        ),
    ]
